Данная лабораторная работа основывается на книге А.Л.Эфроса «Физика и геометрия беспорядка» (Библиотечка Квант) и подготовлена для курса «Наноматериалы», читаемом в весеннем семестре для магистров первого года. Часть материала, связанного с математической справкой, опущена с учетом прохождения студентами курса теории вероятностей и математической статистики.

# 1. Порог протекания

## Эксперимент Ватсона и Лиса

В эксперименте Ватсона и Лиса (Physical Review 1974) был взят кусок экранной сетки квадратной формы, содержащий 137×137 = 18769 узлов. Исследователи припаяли к двум протиповоложным сторонам квадрата электроды и включили сетку в электрическую цепь, чтобы измерить ее сопротивление.

Затем они стали блокировать отдельные узлы и изучать электрическое сопротивление в зависимости от доли блокированных узлов. Блокировка узла состояла в том, что кусачками перерезались все четыре проволоки, связанные с этим узлом.

Каждый новый узел, подлежащий блокировке выбирался среди нетронутых узлов случайно. По мере увеличения доли блокированных узлов $x$ электропроводность сетки уменьшалась. При некотором значении $x_c$ — пороге протекания, когда перерезался последний путь, связывающий левый и правый электроды, электропроводность обращалась в нуль. Было найдено, что для такой сетки $x_c$ = 0,59.

При помощи приведенного ниже кода мы предлагаем вам промоделировать эксперимент Ватсона и Лиса.

In [3]:
import itertools
import numpy as np


def cluster(grid):
    N = grid.shape[0]
    # если в самом левом столбце есть 1, заменяем на 2
    grid[:, 0][grid[:, 0] == 1] = 2
    
    # находим координаты двоек
    nodes2 = np.argwhere(grid == 2)
    
    
    grid[:, 0][grid[:, 0] == 1] = 2

    
    return grid
    


def main(N=5):
    # создаем двумерный массив из NxN невырезанных узлов (0)
    grid = np.zeros((N, N), dtype=int)  
    
    # задаем пары координат для каждого узла
    nodes = list(itertools.product(np.arange(N), np.arange(N)))
    
    # перемешиваем координаты для задания случайного выбора координат
    np.random.shuffle(nodes)
    
    # выбираем случайную координату и переобозначаем ее как вырезанный узел (1)
    for node in nodes:
        print(node)
        grid[node] = 1
        grid = cluster(grid)
        print(grid)
main()

(1, 4)
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(2, 4)
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(1, 0)
[[0 0 0 0 0]
 [2 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(3, 2)
[[0 0 0 0 0]
 [2 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 0]]
(3, 0)
[[0 0 0 0 0]
 [2 0 0 0 1]
 [0 0 0 0 1]
 [2 0 1 0 0]
 [0 0 0 0 0]]
(3, 3)
[[0 0 0 0 0]
 [2 0 0 0 1]
 [0 0 0 0 1]
 [2 0 1 1 0]
 [0 0 0 0 0]]
(2, 3)
[[0 0 0 0 0]
 [2 0 0 0 1]
 [0 0 0 1 1]
 [2 0 1 1 0]
 [0 0 0 0 0]]
(1, 2)
[[0 0 0 0 0]
 [2 0 1 0 1]
 [0 0 0 1 1]
 [2 0 1 1 0]
 [0 0 0 0 0]]
(3, 4)
[[0 0 0 0 0]
 [2 0 1 0 1]
 [0 0 0 1 1]
 [2 0 1 1 1]
 [0 0 0 0 0]]
(2, 0)
[[0 0 0 0 0]
 [2 0 1 0 1]
 [2 0 0 1 1]
 [2 0 1 1 1]
 [0 0 0 0 0]]
(2, 2)
[[0 0 0 0 0]
 [2 0 1 0 1]
 [2 0 1 1 1]
 [2 0 1 1 1]
 [0 0 0 0 0]]
(3, 1)
[[0 0 0 0 0]
 [2 0 1 0 1]
 [2 0 1 1 1]
 [2 1 1 1 1]
 [0 0 0 0 0]]
(1, 3)
[[0 0 0 0 0]
 [2 0 1 1 1]
 [2 0 1 1 1]
 [2 1 1 1 1]
 [0 0 0 0 0]]
(2, 1)
[[0 0 0 0 0]
 [2 0 1 1 1]
 [2 1 1 1 1]
 [2 1

ANimation
http://louistiao.me/posts/notebooks/embedding-matplotlib-animations-in-jupyter-notebooks/